version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ocean_view
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    platform: linux/amd64
    ports:
      - "3334:3334"
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3334
      - DATABASE_URL=postgresql://postgres:postgres@timescaledb:5432/ocean_view?schema=public
    command: pnpm --dir=packages/server dev

volumes:
  timescaledb-data: 