# fly.toml app configuration file generated for oceanview on 2025-05-22T22:27:33+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ocean-staging'
primary_region = 'syd'

[build]
  dockerfile = './Dockerfile.backend'

[env]
  PORT = '3334'

[processes]
  app = "pnpm --filter server run start:docker"

[[mounts]]
  source = 'ovbackend_data'
  destination = '/app/packages/server/prisma'

[http_service]
  internal_port = 3334
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
