# fly.toml for backend only
app = 'oceanview-backend'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile.backend'

[http_service]
  internal_port = 3334
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "ovbackend_data"
  destination = "/app/packages/server/prisma"

# Serve the frontend UI on port 5173
[[services]]
  internal_port = 5173
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 5173