-- Add risk fields to HyperSettings
ALTER TABLE HyperSettings ADD COLUMN gatekeeperThresh REAL NOT NULL DEFAULT 0.55;
ALTER TABLE HyperSettings ADD COLUMN maxDailyLoss REAL NOT NULL DEFAULT 0.03;
ALTER TABLE HyperSettings ADD COLUMN maxOpenRisk REAL NOT NULL DEFAULT 0.05;
ALTER TABLE HyperSettings ADD COLUMN fastMAPeriod INTEGER NOT NULL DEFAULT 50;
ALTER TABLE HyperSettings ADD COLUMN slowMAPeriod INTEGER NOT NULL DEFAULT 200; 