name: E2E Smoke Test

on:
  pull_request:
    branches: 
      - staging
      - main
    paths:
      - 'tests/e2e/**'
      - 'tests/fixtures/**'
      - 'packages/server/src/**'
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Enable pnpm via corepack
        run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Install ONNX runtime
        run: pnpm add -D onnxruntime-node
      
      - name: Setup test directory structure
        run: |
          mkdir -p ml
          mkdir -p tests/e2e
          mkdir -p tests/fixtures
          # Create a dummy model file for testing
          echo "Creating dummy ONNX model for testing"
          touch ml/gatekeeper_v2.onnx
      
      - name: Run E2E smoke test directly
        run: |
          export ONNX_PATH=ml/gatekeeper_v2.onnx
          export NODE_OPTIONS="--no-warnings --max-old-space-size=4096"
          # Skip TypeScript compilation by running the test with ts-node
          npx jest tests/e2e --config jest.config.cjs --runInBand --no-cache --passWithNoTests 