# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  FLY_APP_NAME:  oceanview-staging     # deploy to staging environment

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy app
        run: flyctl deploy --remote-only --app $FLY_APP_NAME
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Run seed script
        run: flyctl ssh console -C "pnpm ts-node scripts/seedAll.ts"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
