name: Index Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install -g @sourcegraph/src-cli

      - name: Index repository
        run: |
          src code-intel upload \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --repo github.com/${{ github.repository }} \
            --commit ${{ github.sha }} \
            --root . 