name: Index Repository

on:
  pull_request:

jobs:
  index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1️⃣ Install pnpm (corepack)
      - name: Enable pnpm via corepack
        run: corepack enable

      # 2️⃣ Setup Node + cache
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      # 3️⃣ Install deps with dev dependencies needed for CI
      - run: pnpm install --frozen-lockfile --ignore-scripts
      
      # 4️⃣ Run clean script
      - run: pnpm -F server run clean
      
      # 5️⃣ Prisma-model check using npx directly
      - run: npx tsx scripts/ci-model-check.ts 