name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "CI check successful" && exit 0 