-- AlterTable
ALTER TABLE "Bot" ADD COLUMN "parentId" INTEGER;

-- CreateTable
CREATE TABLE "Metric" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "botId" INTEGER NOT NULL,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "equity" REAL NOT NULL,
    "pnl" REAL NOT NULL,
    CONSTRAINT "Metric_botId_fkey" FOREIGN KEY ("botId") REFERENCES "Bot" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
